[package]
name = "nut-lock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "nut_lock"

[dependencies]
keyring = "2.0.4"
