/* This SQL script defines the schema for the paradata required to operate Squirrel.
 *
 * Its main purpose is to track processing events, sources, mappings, etc.
 */



-- A mapping between entities from the source and Squirrel.
-- XXX: Source is in catalogue.
CREATE TABLE IF NOT EXISTS mapping (
  local_id         text NOT NULL,
  local_entity     text NOT NULL,

  source_entity_id text NOT NULL,
  source_entity    text NOT NULL,
  source_id        text NOT NULL,

  UNIQUE (local_id, local_entity)
);


CREATE TABLE IF NOT EXISTS round (
  id               number NOT NULL PRIMARY KEY,
  squirrel_version text NOT NULL,
  stamp            timestamp NOT NULL
);


-- Events generated by the ingestion process.
--
-- TODO: Does this help in cleaning unvisited entries? E.g. a file or folder is removed or renamed.
CREATE TABLE IF NOT EXISTS round_event (
  stamp     timestamp NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
  round_id  number NOT NULL,
  -- this should be inside data only when relevant. E.g. anything unrelated to fs entries is not applicable.
  /* source_id text NOT NULL, */
  data      blob NOT NULL,

  FOREIGN KEY (round_id) REFERENCES round (id),
  FOREIGN KEY (source_id) REFERENCES source (id)
);
